
[34m2023-10-31 21:10:55.134[39m | [1m      INFO      [22m | Running validator for subnet: 18 on network: wss://entrypoint-finney.opentensor.ai:443
[34m2023-10-31 21:11:07.894[39m | [1m      INFO      [22m | retrived new questions: ['What is the most important quality you look for in a partner?', 'How do you define love?', 'What is your favorite love story?', 'What is the best way to maintain a healthy relationship?', 'What is the most romantic gesture you have ever received?', 'What is your idea of a perfect date?', 'What is the key to a successful long-term relationship?', 'What is the biggest lesson you have learned from past relationships?', 'What is the role of trust in a relationship?', 'What is your favorite love quote?']
[34m2023-10-31 21:11:07.894[39m | [1m      INFO      [22m | Sent query to miner: 'What is the most important quality you look for in a partner?' using gpt-3.5-turbo
[34m2023-10-31 21:11:07.895[39m | [1m      INFO      [22m | query called in dendrite
[34m2023-10-31 21:11:07.895[39m | [1m      INFO      [22m | forward_called from forward in dendrite
[34m2023-10-31 21:11:07.896[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3858 B | Openai | 5Hddm3iBFD2GLT5ik7LZnT3XJUnRnN8PoeCFgGQgawUVKNm8 | 64.227.114.35:8091 | 0 | Success
[34m2023-10-31 21:11:07.908[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.918[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.927[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.937[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.946[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.956[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.966[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:07.975[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3860 B | Openai | 5HRNcsPbUE2RRGN2DRy6vM8b9yE3gw4yVHciKx5PiGHHUe6A | 167.172.100.157:15000 | 0 | Success
[34m2023-10-31 21:11:07.985[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3860 B | Openai | 5DJe1g7FXa5q7qzRTV5RfkBK5eVtxC3qcyNByJu2zG4htfeZ | 167.172.100.157:9001 | 0 | Success
[34m2023-10-31 21:11:07.994[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3860 B | Openai | 5CkPk7G5tyL4TuPBr5J2HtiacmYk3r5AdUuvxN2fc71SYYCX | 167.172.100.157:9002 | 0 | Success
[34m2023-10-31 21:11:08.003[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3860 B | Openai | 5FyEpSkw2v7Za87pziURZQkuhXcUyn2aF6zxfYX8a8fQcUue | 167.172.100.157:9003 | 0 | Success
[34m2023-10-31 21:11:08.013[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.022[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.031[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.041[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.050[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.060[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5DkH7nPxeSQMCb9CResVYnZy16tkMJvjS6H3mBg5yNE6EBkk | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.069[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5F1tFZXS1RUc6goGgcELvy2ebb5BP7mZkqak2MSt5BVDfwd3 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.078[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5DXMdGKcP3CgxijrnBshriYkpZ3jPSPRtgg15tndq875xEtd | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.087[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5FnJn5VcjyrvP87JtHsYBJMPfhwVRShLufdyT9SxGHEvsnm9 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.097[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5HY3iBivUFi2kLCq7FYbiPiStuf6TWodTFp2RnQe3KDeyV9z | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.106[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5HgDHEagoe5SA4iGwJ1nYDom3wyFe5TUQdYmubLb7gs4xWJp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.115[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5GYqe6adSFLHX7A4Xfr8YUHcV8PD1QjNRwNJaedX5VFcXCxC | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.124[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5GUD1hHj3xPHDRUN8sfvLJMQXdFEMmWGKtR1vZRRKr13hYg2 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.133[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3824 B | Openai | 5EPe2yWwM6nnYzT2rQZhyDUDxP3jj2o4jhjaaVZvnPV42xY6 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:11:08.151[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4016 B | Openai | 5DJe1g7FXa5q7qzRTV5RfkBK5eVtxC3qcyNByJu2zG4htfeZ | 167.172.100.157:9001 | 503 | Service at 167.172.100.157:9001/Openai unavailable.
[34m2023-10-31 21:11:08.160[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4016 B | Openai | 5CkPk7G5tyL4TuPBr5J2HtiacmYk3r5AdUuvxN2fc71SYYCX | 167.172.100.157:9002 | 503 | Service at 167.172.100.157:9002/Openai unavailable.
[34m2023-10-31 21:11:08.179[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.189[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.198[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.208[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.217[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.227[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.236[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.245[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.254[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.264[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.273[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.282[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5DkH7nPxeSQMCb9CResVYnZy16tkMJvjS6H3mBg5yNE6EBkk | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.291[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5F1tFZXS1RUc6goGgcELvy2ebb5BP7mZkqak2MSt5BVDfwd3 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.300[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.309[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5DXMdGKcP3CgxijrnBshriYkpZ3jPSPRtgg15tndq875xEtd | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.318[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5FnJn5VcjyrvP87JtHsYBJMPfhwVRShLufdyT9SxGHEvsnm9 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.327[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5HY3iBivUFi2kLCq7FYbiPiStuf6TWodTFp2RnQe3KDeyV9z | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.337[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5HgDHEagoe5SA4iGwJ1nYDom3wyFe5TUQdYmubLb7gs4xWJp | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.346[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5GYqe6adSFLHX7A4Xfr8YUHcV8PD1QjNRwNJaedX5VFcXCxC | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.354[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5EPe2yWwM6nnYzT2rQZhyDUDxP3jj2o4jhjaaVZvnPV42xY6 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:08.364[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4545 B | Openai | 5GUD1hHj3xPHDRUN8sfvLJMQXdFEMmWGKtR1vZRRKr13hYg2 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:11:10.606[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 9282 B | Openai | 5FyEpSkw2v7Za87pziURZQkuhXcUyn2aF6zxfYX8a8fQcUue | 167.172.100.157:9003 | 200 | Success
[34m2023-10-31 21:11:10.803[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 9282 B | Openai | 5HRNcsPbUE2RRGN2DRy6vM8b9yE3gw4yVHciKx5PiGHHUe6A | 167.172.100.157:15000 | 200 | Success
[34m2023-10-31 21:11:53.245[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 3991 B | Openai | 5Hddm3iBFD2GLT5ik7LZnT3XJUnRnN8PoeCFgGQgawUVKNm8 | 64.227.114.35:8091 | 408 | Timedout after 45.0 seconds.
[34m2023-10-31 21:11:53.255[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.256[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.256[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.256[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.256[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk: As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk: As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.
[34m2023-10-31 21:11:53.257[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.258[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.259[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.259[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.259[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.259[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:53.259[39m | [1m      INFO      [22m | Received chunk:
[34m2023-10-31 21:11:55.375[39m | [1m      INFO      [22m | Response from openai: As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.
[34m2023-10-31 21:11:55.376[39m | [1m      INFO      [22m | Received response: As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual. from miner with UID 0. Assigned score: 0
[34m2023-10-31 21:11:55.378[39m | [1m      INFO      [22m | scores = tensor([0.9000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])
[34m2023-10-31 21:11:55.379[39m | [1m      INFO      [22m | responses_dict is {0: {'response': "As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.As an AI language model, I don't have personal preferences or opinions. However, the most important quality in a partner can vary greatly depending on individual preferences and values. Some common qualities that people often look for in a partner include trustworthiness, compatibility, communication skills, emotional intelligence, kindness, shared values, and a sense of humor. Ultimately, the most important quality will depend on the unique needs and desires of each individual.", 'score': 0}}
[34m2023-10-31 21:11:55.566[39m | [1m      INFO      [22m | step = 0
[34m2023-10-31 21:12:07.567[39m | [1m      INFO      [22m | Sent query to miner: 'How do you define love?' using gpt-3.5-turbo
[34m2023-10-31 21:12:07.568[39m | [1m      INFO      [22m | query called in dendrite
[34m2023-10-31 21:12:07.568[39m | [1m      INFO      [22m | forward_called from forward in dendrite
[34m2023-10-31 21:12:07.570[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3820 B | Openai | 5Hddm3iBFD2GLT5ik7LZnT3XJUnRnN8PoeCFgGQgawUVKNm8 | 64.227.114.35:8091 | 0 | Success
[34m2023-10-31 21:12:07.580[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.591[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.601[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.611[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.621[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.631[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.641[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.651[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5HRNcsPbUE2RRGN2DRy6vM8b9yE3gw4yVHciKx5PiGHHUe6A | 167.172.100.157:15000 | 0 | Success
[34m2023-10-31 21:12:07.660[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5DJe1g7FXa5q7qzRTV5RfkBK5eVtxC3qcyNByJu2zG4htfeZ | 167.172.100.157:9001 | 0 | Success
[34m2023-10-31 21:12:07.670[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5CkPk7G5tyL4TuPBr5J2HtiacmYk3r5AdUuvxN2fc71SYYCX | 167.172.100.157:9002 | 0 | Success
[34m2023-10-31 21:12:07.680[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5FyEpSkw2v7Za87pziURZQkuhXcUyn2aF6zxfYX8a8fQcUue | 167.172.100.157:9003 | 0 | Success
[34m2023-10-31 21:12:07.689[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.698[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.707[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.718[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.727[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.737[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DkH7nPxeSQMCb9CResVYnZy16tkMJvjS6H3mBg5yNE6EBkk | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.747[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5F1tFZXS1RUc6goGgcELvy2ebb5BP7mZkqak2MSt5BVDfwd3 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.755[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DXMdGKcP3CgxijrnBshriYkpZ3jPSPRtgg15tndq875xEtd | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.765[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5FnJn5VcjyrvP87JtHsYBJMPfhwVRShLufdyT9SxGHEvsnm9 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.774[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5HY3iBivUFi2kLCq7FYbiPiStuf6TWodTFp2RnQe3KDeyV9z | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.783[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5HgDHEagoe5SA4iGwJ1nYDom3wyFe5TUQdYmubLb7gs4xWJp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.793[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GYqe6adSFLHX7A4Xfr8YUHcV8PD1QjNRwNJaedX5VFcXCxC | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.802[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GUD1hHj3xPHDRUN8sfvLJMQXdFEMmWGKtR1vZRRKr13hYg2 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.811[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5EPe2yWwM6nnYzT2rQZhyDUDxP3jj2o4jhjaaVZvnPV42xY6 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:07.829[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 3978 B | Openai | 5DJe1g7FXa5q7qzRTV5RfkBK5eVtxC3qcyNByJu2zG4htfeZ | 167.172.100.157:9001 | 503 | Service at 167.172.100.157:9001/Openai unavailable.
[34m2023-10-31 21:12:07.839[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 3978 B | Openai | 5CkPk7G5tyL4TuPBr5J2HtiacmYk3r5AdUuvxN2fc71SYYCX | 167.172.100.157:9002 | 503 | Service at 167.172.100.157:9002/Openai unavailable.
[34m2023-10-31 21:12:07.856[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.866[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.876[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.885[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.895[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.904[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.913[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.923[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.933[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.942[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.952[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.962[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.972[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5F1tFZXS1RUc6goGgcELvy2ebb5BP7mZkqak2MSt5BVDfwd3 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.981[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5DkH7nPxeSQMCb9CResVYnZy16tkMJvjS6H3mBg5yNE6EBkk | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:07.990[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5DXMdGKcP3CgxijrnBshriYkpZ3jPSPRtgg15tndq875xEtd | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.000[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5FnJn5VcjyrvP87JtHsYBJMPfhwVRShLufdyT9SxGHEvsnm9 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.009[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5HY3iBivUFi2kLCq7FYbiPiStuf6TWodTFp2RnQe3KDeyV9z | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.019[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5HgDHEagoe5SA4iGwJ1nYDom3wyFe5TUQdYmubLb7gs4xWJp | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.029[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5GYqe6adSFLHX7A4Xfr8YUHcV8PD1QjNRwNJaedX5VFcXCxC | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.039[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5GUD1hHj3xPHDRUN8sfvLJMQXdFEMmWGKtR1vZRRKr13hYg2 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:08.049[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 4507 B | Openai | 5EPe2yWwM6nnYzT2rQZhyDUDxP3jj2o4jhjaaVZvnPV42xY6 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.111[39m | [1m      INFO      [22m | forward_called from forward in dendrite
[34m2023-10-31 21:12:10.113[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3820 B | Openai | 5Hddm3iBFD2GLT5ik7LZnT3XJUnRnN8PoeCFgGQgawUVKNm8 | 64.227.114.35:8091 | 0 | Success
[34m2023-10-31 21:12:10.123[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.135[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.146[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.157[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.167[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.178[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.189[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.199[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5HRNcsPbUE2RRGN2DRy6vM8b9yE3gw4yVHciKx5PiGHHUe6A | 167.172.100.157:15000 | 0 | Success
[34m2023-10-31 21:12:10.210[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5DJe1g7FXa5q7qzRTV5RfkBK5eVtxC3qcyNByJu2zG4htfeZ | 167.172.100.157:9001 | 0 | Success
[34m2023-10-31 21:12:10.221[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5CkPk7G5tyL4TuPBr5J2HtiacmYk3r5AdUuvxN2fc71SYYCX | 167.172.100.157:9002 | 0 | Success
[34m2023-10-31 21:12:10.231[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3822 B | Openai | 5FyEpSkw2v7Za87pziURZQkuhXcUyn2aF6zxfYX8a8fQcUue | 167.172.100.157:9003 | 0 | Success
[34m2023-10-31 21:12:10.241[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.251[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.262[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.273[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.278[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 3814 B | Openai | 5Ca7YzuPX2WxRzdgET6xnLdYodUyq2TKxp9LVuKAajiYvD7n | 0.0.0.0:0 | None | None
[34m2023-10-31 21:12:10.288[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.298[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DkH7nPxeSQMCb9CResVYnZy16tkMJvjS6H3mBg5yNE6EBkk | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.309[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5F1tFZXS1RUc6goGgcELvy2ebb5BP7mZkqak2MSt5BVDfwd3 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.320[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5DXMdGKcP3CgxijrnBshriYkpZ3jPSPRtgg15tndq875xEtd | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.330[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5FnJn5VcjyrvP87JtHsYBJMPfhwVRShLufdyT9SxGHEvsnm9 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.341[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5HY3iBivUFi2kLCq7FYbiPiStuf6TWodTFp2RnQe3KDeyV9z | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.355[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5HgDHEagoe5SA4iGwJ1nYDom3wyFe5TUQdYmubLb7gs4xWJp | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.365[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GYqe6adSFLHX7A4Xfr8YUHcV8PD1QjNRwNJaedX5VFcXCxC | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.375[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5GUD1hHj3xPHDRUN8sfvLJMQXdFEMmWGKtR1vZRRKr13hYg2 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.385[39m | [34m[1m     DEBUG      [39m[22m | dendrite | --> | 3786 B | Openai | 5EPe2yWwM6nnYzT2rQZhyDUDxP3jj2o4jhjaaVZvnPV42xY6 | 0.0.0.0:0 | 0 | Success
[34m2023-10-31 21:12:10.403[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 9978 B | Openai | 5HRNcsPbUE2RRGN2DRy6vM8b9yE3gw4yVHciKx5PiGHHUe6A | 167.172.100.157:15000 | 200 | Success
[34m2023-10-31 21:12:10.416[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5DvTpiniW9s3APmHRYn8FroUWyfnLtrsid5Mtn5EwMXHN2ed | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.425[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5G3f8VDTT1ydirT3QffnV2TMrNMR2MkQfGUubQNqZcGSj82T | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.435[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5Ehv5XMriPZwNBtYHdQV7VrdbN8MBTDTmQhWprZJXxSiMapR | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.445[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5GcBK8PDrVifV1xAf4Qkkk6KsbsmhDdX9atvk8vyKU8xdU63 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.455[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5CQBJ5q1TXhEue3GprnKZiqPzs3og9ES1w5kNuH82QU51F7C | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.464[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5Gjk2tHMPAov4J9jeCXuHE8TRis2y7teCoUViEUPNjopHg3M | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.474[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5CsvRJXuR955WojnGMdok1hbhffZyB4N5ocrv82f3p5A2zVp | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.483[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5F9jkka5jVkhJakLpUFM7HDLNMW6L2AVqdXjnVkGtPQ2b5H7 | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.493[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5ExmGKJcGNkz7YjtUGkdtRJwxxzbE54T9RNJDs56i739QUYe | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.503[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5GWpLx45mZb2AuBN96eucHgjk1i9FNxb1oSCnW4KJFEx1DFJ | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
[34m2023-10-31 21:12:10.513[39m | [34m[1m     DEBUG      [39m[22m | dendrite | <-- | 5151 B | Openai | 5FcYPfTqHkEydeN3YcGGaBFiZMERVMP5H7p8zGDj35Pc1acB | 0.0.0.0:0 | 422 | Failed to parse with error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai').
Traceback:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 415, in call
    json_response = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('http://0.0.0.0:0/Openai')
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 229, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 233, in query
    result = loop.run_until_complete(self.forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 93, in run_until_complete
    self._run_once()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 129, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 315, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.10/dist-packages/nest_asyncio.py", line 205, in step
    step_orig(task, exc)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 339, in single_axon_response
    return await self.call(
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 430, in call
    bittensor.Synapse.from_headers(synapse.to_headers())
  File "/root/.bittensor/bittensor/bittensor/synapse.py", line 448, in to_headers
    required = schema([self.__class__])["definitions"][self.name].get(
  File "pydantic/schema.py", line 147, in pydantic.schema.schema
  File "pydantic/schema.py", line 582, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 623, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 249, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 217, in pydantic.schema.get_field_info_schema
  File "pydantic/schema.py", line 981, in pydantic.schema.encode_default
  File "/usr/lib/python3.10/typing.py", line 1737, in cast
    def cast(typ, val):
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/subnets/exploitproof-net/bittensor-subnet-template/neurons/validator.py", line 237, in <module>
    main(get_config())
  File "/root/subnets/exploitproof-net/bittensor-subnet-template/neurons/validator.py", line 234, in main
    run_validator_loop(wallet, subtensor, dendrite, metagraph, config, scores)
  File "/root/subnets/exploitproof-net/bittensor-subnet-template/neurons/validator.py", line 201, in run_validator_loop
    for chunk in dendrite.query(metagraph.axons, template.protocol.Openai(openai_input=query, openai_engine=engine), deserialize=True):
  File "/root/.bittensor/bittensor/bittensor/dendrite.py", line 238, in query
    return result
UnboundLocalError: local variable 'result' referenced before assignment
[31m╭─────────────────────────────── [39m[1mTraceback (most recent call last)[31m[22m ────────────────────────────────╮
[31m│[39m /root/.bittensor/bittensor/bittensor/[1mdendrite.py[22m:[94m229[39m in [92mquery[39m                                    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   226 │   │   [33m"""[39m                                                                                [31m│
[31m│[39m   227 │   │   [94mtry[39m:                                                                               [31m│
[31m│[39m   228 │   │   │   loop = asyncio.get_event_loop()                                                [31m│
[31m│[39m [31m❱ [39m229 │   │   │   result = loop.run_until_complete([96mself[39m.forward(*args, **kwargs))                [31m│
[31m│[39m   230 │   │   [94mexcept[39m:                                                                            [31m│
[31m│[39m   231 │   │   │   new_loop = asyncio.new_event_loop()                                            [31m│
[31m│[39m   232 │   │   │   asyncio.set_event_loop(new_loop)                                               [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/local/lib/python3.10/dist-packages/[1mnest_asyncio.py[22m:[94m93[39m in [92mrun_until_complete[39m                 [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m    90 │   │   │   [94mif[39m f [95mis[39m [95mnot[39m future:                                                            [31m│
[31m│[39m    91 │   │   │   │   f._log_destroy_pending = [94mFalse[39m                                             [31m│
[31m│[39m    92 │   │   │   [94mwhile[39m [95mnot[39m f.done():                                                            [31m│
[31m│[39m [31m❱ [39m 93 │   │   │   │   [96mself[39m._run_once()                                                           [31m│
[31m│[39m    94 │   │   │   │   [94mif[39m [96mself[39m._stopping:                                                         [31m│
[31m│[39m    95 │   │   │   │   │   [94mbreak[39m                                                                  [31m│
[31m│[39m    96 │   │   │   [94mif[39m [95mnot[39m f.done():                                                               [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/local/lib/python3.10/dist-packages/[1mnest_asyncio.py[22m:[94m116[39m in [92m_run_once[39m                         [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   113 │   │   │   [94melse[39m [96mmin[39m([96mmax[39m(                                                                  [31m│
[31m│[39m   114 │   │   │   │   scheduled[[94m0[39m]._when - [96mself[39m.time(), [94m0[39m), [94m86400[39m) [94mif[39m scheduled                  [31m│
[31m│[39m   115 │   │   │   [94melse[39m [94mNone[39m)                                                                     [31m│
[31m│[39m [31m❱ [39m116 │   │   event_list = [96mself[39m._selector.select(timeout)                                        [31m│
[31m│[39m   117 │   │   [96mself[39m._process_events(event_list)                                                   [31m│
[31m│[39m   118 │   │                                                                                      [31m│
[31m│[39m   119 │   │   end_time = [96mself[39m.time() + [96mself[39m._clock_resolution                                    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/lib/python3.10/[1mselectors.py[22m:[94m469[39m in [92mselect[39m                                                   [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   466 │   │   │                                                                                  [31m│
[31m│[39m   467 │   │   │   ready = []                                                                     [31m│
[31m│[39m   468 │   │   │   [94mtry[39m:                                                                           [31m│
[31m│[39m [31m❱ [39m469 │   │   │   │   fd_event_list = [96mself[39m._selector.poll(timeout, max_ev)                       [31m│
[31m│[39m   470 │   │   │   [94mexcept[39m [96mInterruptedError[39m:                                                       [31m│
[31m│[39m   471 │   │   │   │   [94mreturn[39m ready                                                               [31m│
[31m│[39m   472 │   │   │   [94mfor[39m fd, event [95min[39m fd_event_list:                                                [31m│
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[1mKeyboardInterrupt
[3mDuring handling of the above exception, another exception occurred:
[31m╭─────────────────────────────── [39m[1mTraceback (most recent call last)[31m[22m ────────────────────────────────╮
[31m│[39m /root/.bittensor/bittensor/bittensor/[1mdendrite.py[22m:[94m233[39m in [92mquery[39m                                    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   230 │   │   [94mexcept[39m:                                                                            [31m│
[31m│[39m   231 │   │   │   new_loop = asyncio.new_event_loop()                                            [31m│
[31m│[39m   232 │   │   │   asyncio.set_event_loop(new_loop)                                               [31m│
[31m│[39m [31m❱ [39m233 │   │   │   result = loop.run_until_complete([96mself[39m.forward(*args, **kwargs))                [31m│
[31m│[39m   234 │   │   │   new_loop.close()                                                               [31m│
[31m│[39m   235 │   │   │   [94mreturn[39m result                                                                  [31m│
[31m│[39m   236 │   │   [94mfinally[39m:                                                                           [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/local/lib/python3.10/dist-packages/[1mnest_asyncio.py[22m:[94m93[39m in [92mrun_until_complete[39m                 [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m    90 │   │   │   [94mif[39m f [95mis[39m [95mnot[39m future:                                                            [31m│
[31m│[39m    91 │   │   │   │   f._log_destroy_pending = [94mFalse[39m                                             [31m│
[31m│[39m    92 │   │   │   [94mwhile[39m [95mnot[39m f.done():                                                            [31m│
[31m│[39m [31m❱ [39m 93 │   │   │   │   [96mself[39m._run_once()                                                           [31m│
[31m│[39m    94 │   │   │   │   [94mif[39m [96mself[39m._stopping:                                                         [31m│
[31m│[39m    95 │   │   │   │   │   [94mbreak[39m                                                                  [31m│
[31m│[39m    96 │   │   │   [94mif[39m [95mnot[39m f.done():                                                               [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/local/lib/python3.10/dist-packages/[1mnest_asyncio.py[22m:[94m129[39m in [92m_run_once[39m                         [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   126 │   │   │   │   [94mbreak[39m                                                                      [31m│
[31m│[39m   127 │   │   │   handle = ready.popleft()                                                       [31m│
[31m│[39m   128 │   │   │   [94mif[39m [95mnot[39m handle._cancelled:                                                      [31m│
[31m│[39m [31m❱ [39m129 │   │   │   │   handle._run()                                                              [31m│
[31m│[39m   130 │   │   handle = [94mNone[39m                                                                      [31m│
[31m│[39m   131 │                                                                                          [31m│
[31m│[39m   132 │   [1m@contextmanager[22m                                                                        [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/lib/python3.10/asyncio/[1mevents.py[22m:[94m80[39m in [92m_run[39m                                                 [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m    77 │                                                                                          [31m│
[31m│[39m    78 │   [94mdef[39m [92m_run[39m([96mself[39m):                                                                        [31m│
[31m│[39m    79 │   │   [94mtry[39m:                                                                               [31m│
[31m│[39m [31m❱ [39m 80 │   │   │   [96mself[39m._context.run([96mself[39m._callback, *[96mself[39m._args)                                 [31m│
[31m│[39m    81 │   │   [94mexcept[39m ([96mSystemExit[39m, [96mKeyboardInterrupt[39m):                                            [31m│
[31m│[39m    82 │   │   │   [94mraise[39m                                                                          [31m│
[31m│[39m    83 │   │   [94mexcept[39m [96mBaseException[39m [94mas[39m exc:                                                       [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/lib/python3.10/asyncio/[1mtasks.py[22m:[94m315[39m in [92m__wakeup[39m                                             [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   312 │   │   │   # Python eval loop would use `.send(value)` method call,                       [31m│
[31m│[39m   313 │   │   │   # instead of `__next__()`, which is slower for futures                         [31m│
[31m│[39m   314 │   │   │   # that return non-generator iterators from their `__iter__`.                   [31m│
[31m│[39m [31m❱ [39m315 │   │   │   [96mself[39m.__step()                                                                  [31m│
[31m│[39m   316 │   │   [96mself[39m = [94mNone[39m  # Needed to break cycles when an exception occurs.                    [31m│
[31m│[39m   317                                                                                            [31m│
[31m│[39m   318                                                                                            [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/local/lib/python3.10/dist-packages/[1mnest_asyncio.py[22m:[94m205[39m in [92mstep[39m                              [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   202 │   [94mdef[39m [92mstep[39m(task, exc=[94mNone[39m):                                                              [31m│
[31m│[39m   203 │   │   curr_task = curr_tasks.get(task._loop)                                             [31m│
[31m│[39m   204 │   │   [94mtry[39m:                                                                               [31m│
[31m│[39m [31m❱ [39m205 │   │   │   step_orig(task, exc)                                                           [31m│
[31m│[39m   206 │   │   [94mfinally[39m:                                                                           [31m│
[31m│[39m   207 │   │   │   [94mif[39m curr_task [95mis[39m [94mNone[39m:                                                          [31m│
[31m│[39m   208 │   │   │   │   curr_tasks.pop(task._loop, [94mNone[39m)                                           [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/lib/python3.10/asyncio/[1mtasks.py[22m:[94m232[39m in [92m__step[39m                                               [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   229 │   │   │   [94mif[39m exc [95mis[39m [94mNone[39m:                                                                [31m│
[31m│[39m   230 │   │   │   │   # We use the `send` method directly, because coroutines                    [31m│
[31m│[39m   231 │   │   │   │   # don't have `__iter__` and `__next__` methods.                            [31m│
[31m│[39m [31m❱ [39m232 │   │   │   │   result = coro.send([94mNone[39m)                                                   [31m│
[31m│[39m   233 │   │   │   [94melse[39m:                                                                          [31m│
[31m│[39m   234 │   │   │   │   result = coro.throw(exc)                                                   [31m│
[31m│[39m   235 │   │   [94mexcept[39m [96mStopIteration[39m [94mas[39m exc:                                                       [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/.bittensor/bittensor/bittensor/[1mdendrite.py[22m:[94m339[39m in [92msingle_axon_response[39m                     [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   336 │   │   │   │   │   )                                                                      [31m│
[31m│[39m   337 │   │   │   │   [94melse[39m:                                                                      [31m│
[31m│[39m   338 │   │   │   │   │   # If not in streaming mode, simply call the axon and get the respons   [31m│
[31m│[39m [31m❱ [39m339 │   │   │   │   │   [94mreturn[39m [94mawait[39m [96mself[39m.call(                                                [31m│
[31m│[39m   340 │   │   │   │   │   │   target_axon=target_axon,                                           [31m│
[31m│[39m   341 │   │   │   │   │   │   synapse=synapse.copy(),                                            [31m│
[31m│[39m   342 │   │   │   │   │   │   timeout=timeout,                                                   [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/.bittensor/bittensor/bittensor/[1mdendrite.py[22m:[94m430[39m in [92mcall[39m                                     [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   427 │   │   │                                                                                  [31m│
[31m│[39m   428 │   │   │   # Log synapse event history                                                    [31m│
[31m│[39m   429 │   │   │   [96mself[39m.synapse_history.append(                                                   [31m│
[31m│[39m [31m❱ [39m430 │   │   │   │   bittensor.Synapse.from_headers(synapse.to_headers())                       [31m│
[31m│[39m   431 │   │   │   )                                                                              [31m│
[31m│[39m   432 │   │   │                                                                                  [31m│
[31m│[39m   433 │   │   │   # Return the updated synapse object after deserializing if requested           [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/.bittensor/bittensor/bittensor/[1msynapse.py[22m:[94m448[39m in [92mto_headers[39m                                [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   445 │   │   # Iterating over the fields of the instance                                        [31m│
[31m│[39m   446 │   │   [94mfor[39m field, value [95min[39m instance_fields.items():                                       [31m│
[31m│[39m   447 │   │   │   # If the object is not optional, serializing it, encoding it, and adding it    [31m│
[31m│[39m [31m❱ [39m448 │   │   │   required = schema([[96mself[39m.[91m__class__[39m])[[33m"definitions"[39m][[96mself[39m.name].get(             [31m│
[31m│[39m   449 │   │   │   │   [33m"required"[39m                                                                 [31m│
[31m│[39m   450 │   │   │   )                                                                              [31m│
[31m│[39m   451                                                                                            [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.schema[39m:[94m147[39m                                                                    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.model_process_schema[39m:[94m582[39m                                                      [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.model_type_schema[39m:[94m623[39m                                                         [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.field_schema[39m:[94m249[39m                                                              [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.get_field_info_schema[39m:[94m217[39m                                                     [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m in [92mpydantic.schema.encode_default[39m:[94m981[39m                                                            [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /usr/lib/python3.10/[1mtyping.py[22m:[94m1737[39m in [92mcast[39m                                                       [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   1734 │   [94mreturn[39m [96mcls[39m                                                                            [31m│
[31m│[39m   1735                                                                                           [31m│
[31m│[39m   1736                                                                                           [31m│
[31m│[39m [31m❱ [39m1737 [94mdef[39m [92mcast[39m(typ, val):                                                                       [31m│
[31m│[39m   1738 │   [33m"""Cast a value to a type.[39m                                                            [31m│
[31m│[39m   1739 │                                                                                         [31m│
[31m│[39m   1740 │   [33mThis returns the value unchanged.  To the type checker this[39m                           [31m│
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[1mKeyboardInterrupt
[3mDuring handling of the above exception, another exception occurred:
[31m╭─────────────────────────────── [39m[1mTraceback (most recent call last)[31m[22m ────────────────────────────────╮
[31m│[39m /root/subnets/exploitproof-net/bittensor-subnet-template/neurons/[1mvalidator.py[22m:[94m237[39m in [92m<module>[39m    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   234 │   run_validator_loop(wallet, subtensor, dendrite, metagraph, config, scores)             [31m│
[31m│[39m   235                                                                                            [31m│
[31m│[39m   236 [94mif[39m [91m__name__[39m == [33m"__main__"[39m:                                                                 [31m│
[31m│[39m [31m❱ [39m237 │   main(get_config())                                                                     [31m│
[31m│[39m   238                                                                                            [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/subnets/exploitproof-net/bittensor-subnet-template/neurons/[1mvalidator.py[22m:[94m234[39m in [92mmain[39m        [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   231 │   my_subnet_uid = metagraph.hotkeys.index(wallet.hotkey.ss58_address)                    [31m│
[31m│[39m   232 │   scores = torch.ones_like(metagraph.S, dtype=torch.float32)                             [31m│
[31m│[39m   233 │                                                                                          [31m│
[31m│[39m [31m❱ [39m234 │   run_validator_loop(wallet, subtensor, dendrite, metagraph, config, scores)             [31m│
[31m│[39m   235                                                                                            [31m│
[31m│[39m   236 [94mif[39m [91m__name__[39m == [33m"__main__"[39m:                                                                 [31m│
[31m│[39m   237 │   main(get_config())                                                                     [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/subnets/exploitproof-net/bittensor-subnet-template/neurons/[1mvalidator.py[22m:[94m201[39m in             [31m│
[31m│[39m [92mrun_validator_loop[39m                                                                               [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   198 │   │   │   all_chunks = []                                                                [31m│
[31m│[39m   199 │   │   │                                                                                  [31m│
[31m│[39m   200 │   │   │   # Query the dendrite and process the chunks as they arrive                     [31m│
[31m│[39m [31m❱ [39m201 │   │   │   [94mfor[39m chunk [95min[39m dendrite.query(metagraph.axons, template.protocol.Openai(openai   [31m│
[31m│[39m   202 │   │   │   │   bt.logging.info([33mf"Received chunk: {[39mchunk[33m}"[39m)                                [31m│
[31m│[39m   203 │   │   │   │   all_chunks.append(chunk)                                                   [31m│
[31m│[39m   204                                                                                            [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m /root/.bittensor/bittensor/bittensor/[1mdendrite.py[22m:[94m238[39m in [92mquery[39m                                    [31m│
[31m│[39m                                                                                                  [31m│
[31m│[39m   235 │   │   │   [94mreturn[39m result                                                                  [31m│
[31m│[39m   236 │   │   [94mfinally[39m:                                                                           [31m│
[31m│[39m   237 │   │   │   [96mself[39m.close_session()                                                           [31m│
[31m│[39m [31m❱ [39m238 │   │   │   [94mreturn[39m result                                                                  [31m│
[31m│[39m   239 │                                                                                          [31m│
[31m│[39m   240 │   [94masync[39m [94mdef[39m [92mforward[39m(                                                                     [31m│
[31m│[39m   241 │   │   [96mself[39m,                                                                              [31m│
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[1mUnboundLocalError: [22mlocal variable [32m'result'[39m referenced before assignment